force-app/main/default/objects/EnhancedPathConfiguration__mdt/EnhancedPathConfiguration__mdt.object-meta.xml
<CustomObject>
    <description>Metadata used to supply configuration data to the Enhanced Path LWC. Has fields: Object API Name, Field API Name, Record Type API Name, Picklist API Value, Guidance For Success, Key Fields, Dependent Fields, Optional Fields, Flow API Name, Show Confetti

Records can be created manually or synced via the QueueableSyncPathAssistants class</description>
    <label>Enhanced Path Configuration</label>
    <pluralLabel>Enhanced Path Configurations</pluralLabel>
</CustomObject>

force-app/main/default/objects/EnhancedPathConfiguration__mdt/fields/DependentFieldApiNames__c.field-meta.xml
<CustomField>
    <fullName>DependentFieldApiNames__c</fullName>
    <inlineHelpText>A comma separated list of Field API Names that will be treated as Required Dependent Fields for this Picklist Value. This is in addition to any field dependencies already defined at the object level and is primarily intended to be used for fields that typically aren&apos;t able to be considered dependent</inlineHelpText>
    <label>Dependent Field API Names</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/EnhancedPathConfiguration__mdt/fields/FlowApiName__c.field-meta.xml
<CustomField>
    <fullName>FlowApiName__c</fullName>
    <inlineHelpText>Which flow should run when a user attempts to update the field to this Picklist Value?</inlineHelpText>
    <label>Flow API Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/EnhancedPathConfiguration__mdt/fields/KeyFieldApiNames__c.field-meta.xml
<CustomField>
    <fullName>KeyFieldApiNames__c</fullName>
    <inlineHelpText>A comma separated list of Field API Names that should be shown as Key Fields for this Picklist Value</inlineHelpText>
    <label>Key Field API Names</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/EnhancedPathConfiguration__mdt/fields/OptionalFieldApiNames__c.field-meta.xml
<CustomField>
    <fullName>OptionalFieldApiNames__c</fullName>
    <inlineHelpText>A comma separated list of Field API Names that will be treated as Optional Dependent Fields for this Picklist Value. This is in addition to any field dependencies already defined at the object level and is primarily intended to be used for fields that typically aren&amp;apos;t able to be considered dependent</inlineHelpText>
    <label>Optional Field API Names</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/EnhancedPathConfiguration__mdt/fields/PicklistApiValue__c.field-meta.xml
<CustomField>
    <fullName>PicklistApiValue__c</fullName>
    <inlineHelpText>The Picklist API Value this Configuration record represents</inlineHelpText>
    <label>Picklist API Value</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/EnhancedPathControllerTest.cls
/**
 * Created by Tyler on 7/8/2025.
 */

@IsTest
private class EnhancedPathControllerTest {
    @IsTest
    static void shouldReturnStepsFromBuildMethod() {
        Test.startTest();
        EnhancedPathController.VALID_FLOW_IDS_BY_API_NAME.put('Test', '301xx000000XyzA');
        List<EnhancedPathController.PathStep> steps = EnhancedPathController.buildPathSteps(
            new List<EnhancedPathConfiguration__mdt>{
                new EnhancedPathConfiguration__mdt(
                    PicklistApiValue__c = 'New',
                    KeyFieldApiNames__c = 'Company, LastName',
                    DependentFieldApiNames__c = 'Email, MobilePhone',
                    OptionalFieldApiNames__c = 'FirstName, Title',
                    FlowApiName__c = 'Test'
                )
            }
        );
        Test.stopTest();
        Assert.areEqual('New', steps[0].value, 'Expected picklist value to be New');
        Assert.areEqual(
            new List<String>{ 'Company', 'LastName' },
            steps[0].keyFields,
            'Expected key field names to match'
        );
        Assert.areEqual(
            new List<String>{ 'Email', 'MobilePhone' },
            steps[0].dependentFields,
            'Expected dependent field names to match'
        );
        Assert.areEqual(
            new List<String>{ 'FirstName', 'Title' },
            steps[0].optionalFields,
            'Expected optional field names to match'
        );
        Assert.areEqual('Test', steps[0].flowApiName, 'Expected flowApiName to be Test');
        Assert.areEqual(true, steps[0].flowValid, 'Expected flowValid to be true');
    }

    @IsTest
    static void shouldReturnStepsWithInvalidFlow() {
        Test.startTest();
        List<EnhancedPathController.PathStep> steps = EnhancedPathController.buildPathSteps(
            new List<EnhancedPathConfiguration__mdt>{
                new EnhancedPathConfiguration__mdt(PicklistApiValue__c = 'New', FlowApiName__c = 'Test')
            }
        );
        Test.stopTest();
        Assert.areEqual(1, steps.size(), 'Expected one path step to be returned');
        Assert.areEqual(false, steps[0].flowValid, 'Expected flowValid to be false');
    }

    @IsTest
    static void shouldReturnEmptyList() {
        Test.startTest();
        List<EnhancedPathController.PathStep> steps = EnhancedPathController.getPathAssistantSteps('A', 'B', 'C');
        Test.stopTest();
        Assert.areEqual(0, steps.size(), 'Expected an empty list to be returned');
    }

    @IsTest
    static void shouldAttemptToCreateAndSaveLogEntry() {
        Test.startTest();
        String nebulaLoggerType = EnhancedPathController.detectNebulaLoggerType();
        Map<String, Object> input = new Map<String, Object>{ 'loggingLevel' => 'ERROR', 'message' => 'Test' };
        Boolean result = EnhancedPathController.createAndSaveLogEntry(nebulaLoggerType, input);
        Test.stopTest();
        Assert.isTrue(result, 'Expected createAndSaveLogEntry to return true');
    }

    @IsTest
    static void handlesSomeBadValueForDetection() {
        Test.startTest();
        Map<String, Object> input = new Map<String, Object>{ 'loggingLevel' => 'ERROR', 'message' => 'Test' };
        Boolean result = EnhancedPathController.createAndSaveLogEntry('SomeBadValue', input);
        Test.stopTest();
        Assert.isFalse(result, 'Expected createAndSaveLogEntry to return false with bad/unexpected logger type');
    }
}