force-app/main/default/objects/EnhancedPathConfiguration__mdt/EnhancedPathConfiguration__mdt.object-meta.xml
<CustomObject>
    <description>Metadata used to supply configuration data to the Enhanced Path LWC. Has fields: Object API Name, Field API Name, Record Type API Name, Picklist API Value, Guidance For Success, Key Fields, Dependent Fields, Optional Fields, Flow API Name, Show Confetti

Records can be created manually or synced via the QueueableSyncPathAssistants class</description>
    <label>Enhanced Path Configuration</label>
    <pluralLabel>Enhanced Path Configurations</pluralLabel>
</CustomObject>

force-app/main/default/objects/EnhancedPathConfiguration__mdt/fields/DependentFieldApiNames__c.field-meta.xml
<CustomField>
    <fullName>DependentFieldApiNames__c</fullName>
    <inlineHelpText>A comma separated list of Field API Names that will be treated as Required Dependent Fields for this Picklist Value. This is in addition to any field dependencies already defined at the object level and is primarily intended to be used for fields that typically aren&apos;t able to be considered dependent</inlineHelpText>
    <label>Dependent Field API Names</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/EnhancedPathConfiguration__mdt/fields/FieldApiName__c.field-meta.xml
<CustomField>
    <fullName>FieldApiName__c</fullName>
    <inlineHelpText>Field API Name this Configuration record is for</inlineHelpText>
    <label>Field API Name</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/EnhancedPathConfiguration__mdt/fields/FlowApiName__c.field-meta.xml
<CustomField>
    <fullName>FlowApiName__c</fullName>
    <inlineHelpText>Which flow should run when a user attempts to update the field to this Picklist Value?</inlineHelpText>
    <label>Flow API Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/EnhancedPathConfiguration__mdt/fields/GuidanceForSuccess__c.field-meta.xml
<CustomField>
    <fullName>GuidanceForSuccess__c</fullName>
    <inlineHelpText>The content that should be displayed as Guidance for Success for this Picklist Value</inlineHelpText>
    <label>Guidance For Success</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/EnhancedPathConfiguration__mdt/fields/IsActive__c.field-meta.xml
<CustomField>
    <fullName>IsActive__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Active?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/EnhancedPathConfiguration__mdt/fields/IsGrouped__c.field-meta.xml
<CustomField>
    <fullName>IsGrouped__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>If this picklist value should be grouped with others under the value defined on the Enhanced Path LWC properties on the Flexipage, check this box. Intended to serve as a way to group Closed, Converted, etc. type values</inlineHelpText>
    <label>Is Grouped</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/EnhancedPathConfiguration__mdt/fields/IsLost__c.field-meta.xml
<CustomField>
    <fullName>IsLost__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>If this Picklist Value &quot;Is Grouped&quot; but is considered a &quot;Lost&quot; value, this box should be checked. Controls whether the previous values in the path show as complete and the color of the path value container (red for lost, green for won)</inlineHelpText>
    <label>Is Lost?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/EnhancedPathConfiguration__mdt/fields/KeyFieldApiNames__c.field-meta.xml
<CustomField>
    <fullName>KeyFieldApiNames__c</fullName>
    <inlineHelpText>A comma separated list of Field API Names that should be shown as Key Fields for this Picklist Value</inlineHelpText>
    <label>Key Field API Names</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/EnhancedPathConfiguration__mdt/fields/ObjectApiName__c.field-meta.xml
<CustomField>
    <fullName>ObjectApiName__c</fullName>
    <inlineHelpText>Object API Name this Configuration record is for</inlineHelpText>
    <label>Object API Name</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/EnhancedPathConfiguration__mdt/fields/OptionalFieldApiNames__c.field-meta.xml
<CustomField>
    <fullName>OptionalFieldApiNames__c</fullName>
    <inlineHelpText>A comma separated list of Field API Names that will be treated as Optional Dependent Fields for this Picklist Value. This is in addition to any field dependencies already defined at the object level and is primarily intended to be used for fields that typically aren&amp;apos;t able to be considered dependent</inlineHelpText>
    <label>Optional Field API Names</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/EnhancedPathConfiguration__mdt/fields/PicklistApiValue__c.field-meta.xml
<CustomField>
    <fullName>PicklistApiValue__c</fullName>
    <inlineHelpText>The Picklist API Value this Configuration record represents</inlineHelpText>
    <label>Picklist API Value</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/EnhancedPathConfiguration__mdt/fields/RecordTypeApiName__c.field-meta.xml
<CustomField>
    <fullName>RecordTypeApiName__c</fullName>
    <inlineHelpText>The Record Type Developer/API Name this Configuration record is for</inlineHelpText>
    <label>Record Type API Name</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/EnhancedPathConfiguration__mdt/fields/ShowConfetti__c.field-meta.xml
<CustomField>
    <fullName>ShowConfetti__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>When a user successfully updates the picklist to this value, should confetti be shown?</inlineHelpText>
    <label>Show Confetti?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/EnhancedPathController.cls
/**
 * Created by Tyler on 7/8/2025.
 */

public with sharing class EnhancedPathController {
    @TestVisible
    private static Map<String, Id> VALID_FLOW_IDS_BY_API_NAME = new Map<String, Id>();

    @AuraEnabled(Cacheable=true)
    public static List<PathStep> getPathAssistantSteps(
        String recordTypeName,
        String objectApiName,
        String fieldApiName
    ) {
        List<FlowDefinitionView> activeFlows = [
            SELECT Id, ApiName
            FROM FlowDefinitionView
            WHERE IsActive = TRUE AND ProcessType IN ('Flow', 'Appointments')
        ];
        for (FlowDefinitionView flow : activeFlows) {
            VALID_FLOW_IDS_BY_API_NAME.put(flow.ApiName, flow.Id);
        }
        List<EnhancedPathConfiguration__mdt> configs = [
            SELECT
                Id,
                PicklistApiValue__c,
                KeyFieldApiNames__c,
                GuidanceForSuccess__c,
                FlowApiName__c,
                DependentFieldApiNames__c,
                OptionalFieldApiNames__c,
                IsGrouped__c,
                IsLost__c,
                ShowConfetti__c
            FROM EnhancedPathConfiguration__mdt
            WHERE
                ObjectApiName__c = :objectApiName
                AND FieldApiName__c = :fieldApiName
                AND RecordTypeApiName__c = :recordTypeName
                AND IsActive__c = TRUE
        ];
        List<PathStep> steps = buildPathSteps(configs);
        return steps;
    }

    @TestVisible
    private static List<PathStep> buildPathSteps(List<EnhancedPathConfiguration__mdt> configs) {
        List<PathStep> steps = new List<PathStep>();
        for (EnhancedPathConfiguration__mdt step : configs) {
            List<String> keyFields = new List<String>();
            List<String> dependentFields = new List<String>();
            List<String> optionalFields = new List<String>();
            if (String.isNotBlank(step.KeyFieldApiNames__c)) {
                keyFields = step.KeyFieldApiNames__c.replaceAll(' ', '').trim().split(',');
            }
            if (String.isNotBlank(step.DependentFieldApiNames__c)) {
                dependentFields = step.DependentFieldApiNames__c.replaceAll(' ', '').trim().split(',');
            }
            if (String.isNotBlank(step.OptionalFieldApiNames__c)) {
                optionalFields.addAll(step.OptionalFieldApiNames__c.replaceAll(' ', '').trim().split(','));
            }
            if (String.isNotBlank(step.FlowApiName__c)) {
                step.FlowApiName__c = VALID_FLOW_IDS_BY_API_NAME.containsKey(
                        step.FlowApiName__c.replaceAll(' ', '').trim()
                    )
                    ? step.FlowApiName__c.replaceAll(' ', '').trim()
                    : null;
            }
            steps.add(
                new PathStep(
                    step.PicklistApiValue__c,
                    step.GuidanceForSuccess__c,
                    keyFields,
                    step.FlowApiName__c,
                    step.FlowApiName__c != null ? true : false,
                    dependentFields,
                    optionalFields,
                    step.IsGrouped__c,
                    step.IsLost__c,
                    step.ShowConfetti__c
                )
            );
        }
        return steps;
    }

    @AuraEnabled
    public static String detectNebulaLoggerType() {
        System.Callable unlockedNebulaLogger = (System.Callable) Type.forName('CallableLogger')?.newInstance();
        System.Callable lockedNebulaLogger = (System.Callable) Type.forName('Nebula.CallableLogger')?.newInstance();
        String nebulaLoggerType = unlockedNebulaLogger != null
            ? 'CallableLogger'
            : lockedNebulaLogger != null ? 'Nebula.CallableLogger' : 'Not Present';
        return nebulaLoggerType;
    }

    @AuraEnabled
    public static Boolean createAndSaveLogEntry(String nebulaLoggerType, Map<String, Object> input) {
        System.Callable dynamicLogger = (System.Callable) Type.forName(
                nebulaLoggerType == 'Not Present' ? 'MockEnhancedPathCallable' : nebulaLoggerType
            )
            ?.newInstance();
        if (dynamicLogger == null) {
            return false;
        }
        Map<String, Object> newEntryOutput = (Map<String, Object>) dynamicLogger.call('newEntry', input);
        Boolean newEntrySuccess = (Boolean) newEntryOutput.get('isSuccess');
        if (!newEntrySuccess) {
            throw new AuraHandledException(
                'Failed to create Nebula Logger log entry: ' + newEntryOutput.get('exceptionMessage')
            );
        }
        Map<String, Object> saveLogOutput = (Map<String, Object>) dynamicLogger.call('saveLog', null);
        Boolean saveLogSuccess = (Boolean) saveLogOutput.get('isSuccess');
        if (!saveLogSuccess) {
            throw new AuraHandledException(
                'Failed to create Nebula Logger log entry: ' + saveLogOutput.get('exceptionMessage')
            );
        }
        return true;
    }
    public class PathStep {
        @AuraEnabled
        public String value;
        @AuraEnabled
        public String guidance;
        @AuraEnabled
        public List<String> keyFields;
        @AuraEnabled
        public String flowApiName;
        @AuraEnabled
        public Boolean flowValid;
        @AuraEnabled
        public List<String> dependentFields;
        @AuraEnabled
        public List<String> optionalFields;
        @AuraEnabled
        public Boolean isGrouped;
        @AuraEnabled
        public Boolean isLost;
        @AuraEnabled
        public Boolean showConfetti;
        public PathStep(
            String value,
            String guidance,
            List<String> keyFields,
            String flowApiName,
            Boolean flowValid,
            List<String> dependentFields,
            List<String> optionalFields,
            Boolean isGrouped,
            Boolean isLost,
            Boolean showConfetti
        ) {
            this.value = value;
            this.guidance = guidance != null ? guidance : '';
            this.keyFields = keyFields;
            this.flowApiName = flowApiName;
            this.flowValid = flowValid;
            this.dependentFields = dependentFields;
            this.optionalFields = optionalFields;
            this.isGrouped = isGrouped;
            this.isLost = isLost;
            this.showConfetti = showConfetti;
        }
    }
}